version: '3.8'

services:
  gym-bot:
    build: .
    container_name: gym-bot
    environment:
      - TELEGRAM_BOT_TOKEN=ВАШ_ТОКЕН_ЗДЕСЬ
      - CHAT_ID=ВАШ_CHAT_ID_ЗДЕСЬ
      - START_DATE=2025-03-17  # Укажите нужную стартовую дату в формате YYYY-MM-DD
    restart: unless-stopped
